### ISSUE TITLE
Reporter throws unhandledPromiseRejectionWarning after tests completion

### ISSUE THREAD

**Issue by lhorak** [DevExpress/testcafe-reporter-spec#2] opened 2017-07-28 13:00 UTC
When using this reporter, after all the tests are done UnhandledPromiseRejection is shown in console and the process never exits:

(node:62612) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: this.moment.duration(...).format is not a function
(node:62612) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by AlexanderMoskovkin** [comment] 2017-07-31 08:54
Hi @lhorak,

The issue is unknown for us. Could you please clarify how do you use the module? Do you just run tests via [TestCafe CLI](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html) with default reporter?

**Comment by lhorak** [comment] 2017-07-31 10:51
Hi @AlexanderMoskovkin ,

I run it using CLI with default reporter.
My setup: 
node 6.9.1
Mac OS X Sierra 10.12.6 (MBP)
chrome

When I specify different reporter, this problem doesn't occur.

**Comment by brekk** [comment] 2017-10-11 22:57
Hi there,

What is the status of this issue? I am able to reproduce, and the error stack is:
```
TypeError: this.moment.duration(...).format is not a function
    at ReporterPluginHost.reportTaskDone (/frontend/node_modules/testcafe-reporter-spec/lib/index.js:95:64)
    at Task.<anonymous> (/frontend/node_modules/testcafe/lib/reporter/index.js:135:26)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at Task.emit (events.js:207:7)
    at BrowserJob.<anonymous> (/frontend/node_modules/testcafe/lib/runner/task.js:79:59)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at BrowserJob.emit (events.js:207:7)
    at /frontend/node_modules/testcafe/lib/runner/browser-job.js:178:51
```

Is there any traction on this?

Thanks,

Brekk

**Comment by AndreyBelym** [comment] 2017-10-12 07:44
Hello @brekk,

likely it is a package manager issue, check https://github.com/DevExpress/testcafe/issues/1750 for more information and possible sollutions.

**Comment by AlexanderMoskovkin** [comment] 2017-10-12 09:53
I've investigated it and described the cause of the problem and ways to resolve it in the following post: https://github.com/DevExpress/testcafe/issues/1750#issuecomment-328922603. So, I close this as a duplicate

**Closed as completed by AlexanderMoskovkin** 2017-10-12 09:53 UTC
